<?php
require_once "ChiTietDon.php";
require_once "ChiTietMay.php";

class ChiTietPhuc extends ChiTietMay
{
    private $soLuongChiTietCon;
    private $dsChiTietCon = [];
    private $loaiChiTiet;

    public function nhap()
    {
        parent::nhap(); // TODO: Change the autogenerated stub
        $this->soLuongChiTietCon = readline("Co Bao Nhieu Chi Tiet:");
        if (is_numeric($this->soLuongChiTietCon)) {
            for ($i = 0; $i < $this->soLuongChiTietCon; $i++) {
                $this->loaiChiTiet = readline("Chi Tiet Don => Nhap 1 || Chi Tiet Phuc => Nhap 2 :");
                if($this->loaiChiTiet == 1 || $this->loaiChiTiet == 2){
                    if ($this->loaiChiTiet == 1) {
                        $chiTietDon = new ChiTietDon();
                        $chiTietDon->nhap();
                        $this->dsChiTietCon[] = $chiTietDon;
                    } else {
                        $chiTietPhuc = new ChiTietPhuc();
                        $chiTietPhuc->nhap();
                        $this->dsChiTietCon[] = $chiTietPhuc;
                    }
                }
                else{
                    echo"vui long chon chi chon 1 hoac 2 ";
                }
            }
        } else {
            echo "vui long nhap lai,so luong phai la con so";
            $this->nhap();
        }
    }

    public function xuat()
    {
        for ($i = 0; $i < $this->soLuongChiTietCon; $i++) {
            $this->dsChiTietCon[$i]->xuat();
        }
    }

    public function tinhTien()
    {
        if(sizeof($this->dsChiTietCon)==0){
            echo "khong co bat ki chi tiet con nao de tinh";
            die();
        }
        else{
            $tongTien = 0;
            for ($i = 0; $i < $this->soLuongChiTietCon; $i++) {
                $tongTien += $this->dsChiTietCon[$i]->tinhTien();
            }
            return $tongTien;
        }
    }

    public function tinhKhoiLuong()
    {
        // TODO: Implement tinhKhoiLuong() method.
        if(sizeof($this->dsChiTietCon)==0){
            echo"khong co bat ki chi tiet con nao de tinh";
        }else{
            $tongKhoiLuong = 0;
            for ($i = 0; $i < $this->soLuongChiTietCon; $i++) {
                $tongKhoiLuong += $this->dsChiTietCon[$i]->tinhKhoiLuong();
            }
            return $tongKhoiLuong;
        }
    }
}
