<?php
require_once "ChiTietMay.php";

class ChiTietDon extends ChiTietMay
{
    private $gia;
    private $khoiLuong;

    /**
     * @return mixed
     */
    public function nhap()
    {
        parent::nhap(); // TODO: Change the autogenerated stub
        $this->gia = readline('Nhap Gia:');
        $this->khoiLuong = readline('Nhap Khoi Luong:');
        if (is_numeric($this->gia) && is_numeric($this->khoiLuong)) {
            return $this;
        } else {
            echo "gia va so luong la so . vui long nhap lai \n";
            $this->nhap();
        }
    }

    public function xuat()
    {
        parent::xuat();
        echo "Gia Tien :" . $this->gia . "\n";
        echo "Khoi Luong:" . $this->khoiLuong . "\n";
    }

    public function tinhTien()
    {
        // TODO: Implement TinhTien() method.
        return $this->gia;
    }

    public function tinhKhoiLuong()
    {
        // TODO: Implement TinhKhoiLuong() method.
        return $this->khoiLuong;
    }
}






